/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAltaRouteImport } from './routes/_app/alta'
import { Route as AppBajaRouteImport } from './routes/_app/baja'
import { Route as AppCalidadRouteImport } from './routes/_app/calidad'
import { Route as AppCierreRouteImport } from './routes/_app/cierre'
import { Route as AppEquipoRouteImport } from './routes/_app/equipo'
import { Route as AppLibroRouteImport } from './routes/_app/libro'
import { Route as AppMovimientosRouteImport } from './routes/_app/movimientos'
import { Route as AppOrganizacionRouteImport } from './routes/_app/organizacion'
import { Route as AppRegistroRouteImport } from './routes/_app/registro'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAltaRoute = AppAltaRouteImport.update({
  id: '/alta',
  path: '/alta',
  getParentRoute: () => AppRoute,
} as any)
const AppBajaRoute = AppBajaRouteImport.update({
  id: '/baja',
  path: '/baja',
  getParentRoute: () => AppRoute,
} as any)
const AppCalidadRoute = AppCalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => AppRoute,
} as any)
const AppCierreRoute = AppCierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppLibroRoute = AppLibroRouteImport.update({
  id: '/libro',
  path: '/libro',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimientosRoute = AppMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizacionRoute = AppOrganizacionRouteImport.update({
  id: '/organizacion',
  path: '/organizacion',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistroRoute = AppRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/alta': typeof AppAltaRoute
  '/baja': typeof AppBajaRoute
  '/calidad': typeof AppCalidadRoute
  '/cierre': typeof AppCierreRoute
  '/equipo': typeof AppEquipoRoute
  '/libro': typeof AppLibroRoute
  '/movimientos': typeof AppMovimientosRoute
  '/organizacion': typeof AppOrganizacionRoute
  '/registro': typeof AppRegistroRoute
}
export interface FileRoutesByTo {
  '/alta': typeof AppAltaRoute
  '/baja': typeof AppBajaRoute
  '/calidad': typeof AppCalidadRoute
  '/cierre': typeof AppCierreRoute
  '/equipo': typeof AppEquipoRoute
  '/libro': typeof AppLibroRoute
  '/movimientos': typeof AppMovimientosRoute
  '/organizacion': typeof AppOrganizacionRoute
  '/registro': typeof AppRegistroRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/alta': typeof AppAltaRoute
  '/_app/baja': typeof AppBajaRoute
  '/_app/calidad': typeof AppCalidadRoute
  '/_app/cierre': typeof AppCierreRoute
  '/_app/equipo': typeof AppEquipoRoute
  '/_app/libro': typeof AppLibroRoute
  '/_app/movimientos': typeof AppMovimientosRoute
  '/_app/organizacion': typeof AppOrganizacionRoute
  '/_app/registro': typeof AppRegistroRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alta'
    | '/baja'
    | '/calidad'
    | '/cierre'
    | '/equipo'
    | '/libro'
    | '/movimientos'
    | '/organizacion'
    | '/registro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alta'
    | '/baja'
    | '/calidad'
    | '/cierre'
    | '/equipo'
    | '/libro'
    | '/movimientos'
    | '/organizacion'
    | '/registro'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/alta'
    | '/_app/baja'
    | '/_app/calidad'
    | '/_app/cierre'
    | '/_app/equipo'
    | '/_app/libro'
    | '/_app/movimientos'
    | '/_app/organizacion'
    | '/_app/registro'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alta': {
      id: '/_app/alta'
      path: '/alta'
      fullPath: '/alta'
      preLoaderRoute: typeof AppAltaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baja': {
      id: '/_app/baja'
      path: '/baja'
      fullPath: '/baja'
      preLoaderRoute: typeof AppBajaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calidad': {
      id: '/_app/calidad'
      path: '/calidad'
      fullPath: '/calidad'
      preLoaderRoute: typeof AppCalidadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cierre': {
      id: '/_app/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof AppCierreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipo': {
      id: '/_app/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libro': {
      id: '/_app/libro'
      path: '/libro'
      fullPath: '/libro'
      preLoaderRoute: typeof AppLibroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimientos': {
      id: '/_app/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AppMovimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizacion': {
      id: '/_app/organizacion'
      path: '/organizacion'
      fullPath: '/organizacion'
      preLoaderRoute: typeof AppOrganizacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registro': {
      id: '/_app/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AppRegistroRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAltaRoute: typeof AppAltaRoute
  AppBajaRoute: typeof AppBajaRoute
  AppCalidadRoute: typeof AppCalidadRoute
  AppCierreRoute: typeof AppCierreRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppLibroRoute: typeof AppLibroRoute
  AppMovimientosRoute: typeof AppMovimientosRoute
  AppOrganizacionRoute: typeof AppOrganizacionRoute
  AppRegistroRoute: typeof AppRegistroRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAltaRoute: AppAltaRoute,
  AppBajaRoute: AppBajaRoute,
  AppCalidadRoute: AppCalidadRoute,
  AppCierreRoute: AppCierreRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppLibroRoute: AppLibroRoute,
  AppMovimientosRoute: AppMovimientosRoute,
  AppOrganizacionRoute: AppOrganizacionRoute,
  AppRegistroRoute: AppRegistroRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
